import Link from 'next/link'
import './globals.css'
import { AR_One_Sans, Inter } from 'next/font/google'
import Image from 'next/image'

// // const inter = Inter({ subsets: ['latin'] })
// const openSans = AR_One_Sans(
//   {
//     subsets: ['latin'],
//     weight: ['400', '500', '600', '700']
//   }
// )
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` bg-home`}>
          <header className='flex justify-between items-center h-[130px] py-2 px-40'>
            <Image alt='logo' width={350} src={"/sb.png"}  height={200}/>
            <ul className='flex text-xl gap-10 uppercase'>
              <li><Link href={""}>Inicio</Link></li>
              <li><Link href={""}>Biblioteca</Link></li>
              <li><Link href={""}>Noticias</Link></li>
              <li><Link href={""}>Gallería</Link></li>
            </ul>
          </header>
        {children}
      </body>
    </html>
  )
}
